### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'controller')

### ISSUE THREAD

**Issue by iamfrego** [shailesh-ladumor/laravel-pwa#7]
hi, ive do all the step in the tutorial but i get this error when i load the page, im using Laravel 8 with the Vuejs scaffolding, can u help me pls?

**Comment by shailesh-ladumor** [comment]
what error are you gtting? please provide more details

**Comment by iamfrego** [comment]
TypeError: Cannot read properties of undefined (reading 'controller')

in this function

![Immagine 2022-09-09 083514](https://user-images.githubusercontent.com/51087527/189286691-e4a254a0-93b7-4a2c-9743-b5414b0344ae.png)


in console i see this

![image](https://user-images.githubusercontent.com/51087527/189286887-16e57510-3d80-462a-b5df-38406bf1cd4f.png)


![image](https://user-images.githubusercontent.com/51087527/189286920-4aef8136-5957-40fb-acf1-39209e9668d8.png)


i dont have more info about this error

**Comment by Nielson** [comment]
Hi @iamfrego !

The issue is that your page isn't being server over https. 

I had this very same problem and I solved it using this workaround: 

In Chrome, go to: chrome://flags/#unsafely-treat-insecure-origin-as-secure
Add your site in the input field and restart Chrome. Don't forget to set is "Enabled".

![image](https://user-images.githubusercontent.com/1812655/193533759-81e54851-5788-41e4-a8a8-86d447b31ceb.png)

Solution found on https://stackoverflow.com/questions/52299246/cant-find-serviceworker-in-navigator-anymore.

Hope it works out for you! If using Laravel Valet, you can also enable SSL throught that.

**Comment by dieudonneopilam** [comment]
merci beaoucoup chez moi ça marche bien

**Comment by iamfrego** [comment]
Thanks so much!!!
